on: 
  push: 
    branches:
      - main
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  build:
    name: .NET Build
    uses: build.yml
    with:
      build-args: -r win-x64 -p:PublishSingleFile=true --self-contained true 
      build-configuration: Release
      path: ../..
